wandb_version: 1

project_name:
  desc: null
  value: CKA experiemnt
arch:
  desc: null
  value:
    conv_dim: 16
    latent_dim: 4
seed:
  desc: null
  value: 123
trainer:
  desc: null
  value:
    epochs: 100
    save_dir: saved/
    save_period: 10
    verbosity: 2
    monitor: val_loss
    early_stop: 10
    tensorboard: true
data_loader:
  desc: null
  value:
    type: MnistDataLoader
    args:
      data_dir: data/
      batch_size: 256
      shuffle: true
      validation_split: 0.1
      num_workers: 2
optimizer:
  desc: null
  value:
    type: Adam
    args:
      lr: 0.001
      weight_decay: 0
      amsgrad: true
metrics:
  desc: null
  value:
  - accuracy
  - top_k_acc
run_id:
  desc: null
  value: '20230715123027'
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689420629.14727
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.10.12
      5: 0.15.5
      8:
      - 1
      - 4
      - 5
